### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by Archikrim** [Archikrim/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by ArchikrimSecond** [comment]
Phone: +38(099)-058-13-20

Email: archikrim@gmail.com

Facebook: https://www.facebook.com/artur.suleymanov10

Instagram: https://www.instagram.com/archikrim/

Github: https://github.com/Archikrim

LinkedIn: https://www.linkedin.com/in/artur-suleimanov/
