### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by Archikrim** [Archikrim/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by ArchikrimSecond** [comment]
**LANGUAGES**
🇺🇦 UKRAINIAN 🇷🇺 RUSSIAN 🇺🇸 ENGLISH

**SKILLS**
UNDERSTANDING OF OOP AND SOLID PRINCIPLES, KNOWLEDGE OF THE C# PROGRAMMING LANGUAGE, PROGRAMMING IN C/C++(BASIC), WINDOWS FORMS, WPF+MVVM, EXPERIENCE WITH MS SQL SERVER DATABASES, T-SQL, HTML, CSS, JAVASCRIPT(BASIC), ASP.NET(BASIC), ADO.NET, AGILE (SCRUM), UML, DESIGN PATTERNS, GIT, VAGRANT

**CHARACTER**

- CONFIDENT
- SHARP-WITTED 
- LEARNING AGILITY 
- SEFL MOTIVATED 
- TEAM PLAYER 
- SUCCESS ORIENTED 
- ADAPT WELL TO NEW SITUATIONS 
- DREAMER
- OBSERVANT
- CURIOUS 
- HAVE PLANNING SKILLS 
- QUALITY-ORIENTED 

**LIKES 😃**
TRAVELLING AND DISCOVERING NEW PLACES, READING, INTELLECTUAL GAMES, MOVIES AND TV SHOWS, COOKING, LEARNING, ENJOY SPENDING TIME WITH SMART PEOPLE WITH GOOD SENSE OF HUMOR.

**DISLIKES 😞**
DEGRADATION, COMMUNICATION WITHOUT ANY SENSE, ENVY, WASTING LIFE ON USELESS THINGS, CHEATING AND LIE, GREED. 

**IT EDUCATION** 
2019 – nowadays 

- IT Step Academy 
- YouTube
- Books
- Solo learn
- CodecademyGo
- Stepic
- Codewars
- Different free resources
